services:
  frontend:
    image: localhost:5000/bhs-game-fuse/frontend:latest
    container_name: gamefuse-frontend
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s http://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3 
      start_period: 10s
    networks:
      - gamefuse
    restart: unless-stopped

networks:
  gamefuse:
    external: true
