export const GENRES = ['Action', 'Adventure', 'Animation & Modeling', 'Casual', 'Design & Illustration', 'Documentary', 'Early Access', 'Education', 'Episodic', 'Free to Play', 'Game Development', 'Indie', 'Massively Multiplayer', 'Movie', 'Racing', 'RPG', 'Short', 'Simulation', 'Software Training', 'Sports', 'Strategy', 'Tutorial', 'Utilities', 'Video Production', 'Web Publishing', '360 Video', 'Accounting', 'Audio Production', 'Gore', 'Nudity', 'Sexual Content', 'Violent'];

export const TAGS = ['1980s', "1990's", '2.5D', '2D', '2D Fighter', '2D Platformer', '360 Video', '3D', '3D Fighter', '3D Platformer', '3D Vision', '4 Player Local', '4X', '6DOF', '8-bit Music', 'ATV', 'Abstract', 'Action', 'Action RPG', 'Action RTS', 'Action Roguelike', 'Action-Adventure', 'Addictive', 'Adventure', 'Agriculture', 'Aliens', 'Alternate History', 'Ambient', 'America', 'Animation & Modeling', 'Anime', 'Arcade', 'Archery', 'Arena Shooter', 'Artificial Intelligence', 'Assassin', 
    'Asymmetric VR', 'Asynchronous Multiplayer', 'Atmospheric', 'Audio Production', 'Auto Battler', 'Automation', 'Automobile Sim', 'BMX', 'Base-Building', 'Baseball', 'Based On A Novel', 'Basketball', 'Batman', 'Battle Royale', "Beat 'em up", 'Beautiful', 'Benchmark', 'Bikes', 'Birds', 'Blood', 'Board Game', 'Boomer Shooter', 'Boss Rush', 'Bowling', 'Boxing', 'Building', 'Bullet Hell', 'Bullet Time', 'CRPG', 'Capitalism', 'Card Battler', 'Card Game', 'Cartoon', 'Cartoony', 'Casual', 'Cats', 
    'Character Action Game', 'Character Customization', 'Chess', 'Choices Matter', 'Choose Your Own Adventure', 'Cinematic', 'City Builder', 'Class-Based', 'Classic', 'Clicker', 'Co-op', 'Co-op Campaign', 'Coding', 'Cold War', 'Collectathon', 'Colony Sim', 'Colorful', 'Combat', 'Combat Racing', 'Comedy', 'Comic Book', 'Competitive', 'Conspiracy', 'Controller', 'Conversation', 'Cooking', 'Cozy', 'Crafting', 'Creature Collector', 'Cricket', 'Crime', 'Crowdfunded', 'Cult Classic', 'Cute', 'Cyberpunk', 
    'Cycling', 'Dark', 'Dark Comedy', 'Dark Fantasy', 'Dark Humor', 'Dating Sim', 'Deckbuilding', 'Demons', 'Design & Illustration', 'Destruction', 'Detective', 'Dice', 'Difficult', 'Dinosaurs', 'Diplomacy', 'Documentary', 'Dog', 'Dragons', 'Drama', 'Driving', 'Dungeon Crawler', 'Dungeons & Dragons', 'Dwarf', 'Dynamic Narration', 'Dystopian ', 'Early Access', 'Economy', 'Education', 'Electronic', 'Electronic Music', 'Elf', 'Emotional', 'Epic', 'Episodic', 'Escape Room', 'Experience', 'Experimental', 
    'Exploration', 'Extraction Shooter', 'FMV', 'FPS', 'Faith', 'Family Friendly', 'Fantasy', 'Farming', 'Farming Sim', 'Fast-Paced', 'Feature Film', 'Female Protagonist', 'Fighting', 'First-Person', 'Fishing', 'Flight', 'Football', 'Football (American)', 'Football (Soccer)', 'Foreign', 'Fox', 'Free to Play', 'Funny', 'Futuristic', 'Gambling', 'Game Development', 'GameMaker', 'Games Workshop', 'Gaming', 'God Game', 'Golf', 'Gore', 'Gothic', 'Grand Strategy', 'Great Soundtrack', 'Grid-Based Movement', 
    'Gun Customization', 'Hack and Slash', 'Hacking', 'Hand-drawn', 'Hardware', 'Heist', 'Hentai', 'Hero Shooter', 'Hex Grid', 'Hidden Object', 'Historical', 'Hobby Sim', 'Hockey', 'Horror', 'Horses', 'Hunting', 'Idler', 'Illuminati', 'Immersive', 'Immersive Sim', 'Indie', 'Instrumental Music', 'Intentionally Awkward Controls', 'Interactive Fiction', 'Inventory Management', 'Investigation', 'Isometric', 'JRPG', 'Jet', 'Job Simulator', 'Jump Scare', 'Kickstarter', 'LEGO', 'LGBTQ+', 'Lara Croft', 'Lemmings', 
    'Level Editor', 'Life Sim', 'Linear', 'Local Co-Op', 'Local Multiplayer', 'Logic', 'Loot', 'Looter Shooter', 'Lore-Rich', 'Lovecraftian', 'MMORPG', 'MOBA', 'Magic', 'Mahjong', 'Management', 'Mars', 'Martial Arts', 'Massively Multiplayer', 'Masterpiece', 'Match 3', 'Mature', 'Mechs', 'Medical Sim', 'Medieval', 'Memes', 'Metroidvania', 'Military', 'Mini Golf', 'Minigames', 'Minimalist', 'Mining', 'Mod', 'Moddable', 'Modern', 'Motocross', 'Motorbike', 'Mouse only', 'Movie', 'Multiplayer', 'Multiple Endings', 
    'Music', 'Music-Based Procedural Generation', 'Musou', 'Mystery', 'Mystery Dungeon', 'Mythology', 'NSFW', 'Narration', 'Narrative', 'Nature', 'Naval', 'Naval Combat', 'Ninja', 'Noir', 'Nonlinear', 'Nostalgia', 'Nudity', 'Offroad', 'Old School', 'On-Rails Shooter', 'Online Co-Op', 'Open World', 'Open World Survival Craft', 'Otome', 'Outbreak Sim', 'Parkour', 'Parody ', 'Party', 'Party Game', 'Party-Based RPG', 'Perma Death', 'Philosophical', 'Photo Editing', 'Physics', 'Pinball', 'Pirates', 'Pixel Graphics', 
    'Platformer', 'Point & Click', 'Political', 'Political Sim', 'Politics', 'Pool', 'Post-apocalyptic', 'Precision Platformer', 'Procedural Generation', 'Programming', 'Psychedelic', 'Psychological', 'Psychological Horror', 'Puzzle', 'Puzzle-Platformer', 'PvE', 'PvP', 'Quick-Time Events', 'RPG', 'RPGMaker', 'RTS', 'Racing', 'Real Time Tactics', 'Real-Time', 'Real-Time with Pause', 'Realistic', 'Reboot', 'Relaxing', 'Remake', 'Replay Value', 'Resource Management', 'Retro', 'Rhythm', 'Robots', 'Rock Music', 'Rogue-like', 
    'Rogue-lite', 'Roguelike Deckbuilder', 'Roguevania', 'Romance', 'Rome', 'Rugby', 'Runner', 'Sailing', 'Sandbox', 'Satire', 'Sci-fi', 'Science', 'Score Attack', 'Sequel', 'Sexual Content', "Shoot 'Em Up", 'Shooter', 'Shop Keeper', 'Short', 'Side Scroller', 'Silent Protagonist', 'Simulation', 'Singleplayer', 'Skateboarding', 'Skating', 'Skiing', 'Sniper', 'Snooker', 'Snow', 'Snowboarding', 'Social Deduction', 'Software', 'Software Training', 'Sokoban', 'Solitaire', 'Souls-like', 'Soundtrack', 'Space', 'Space Sim', 'Spaceships', 
    'Spectacle fighter', 'Spelling', 'Split Screen', 'Sports', 'Stealth', 'Steam Machine', 'Steampunk', 'Story Rich', 'Strategy', 'Strategy RPG', 'Stylized', 'Submarine', 'Superhero', 'Supernatural', 'Surreal', 'Survival', 'Survival Horror', 'Swordplay', 'Tabletop', 'Tactical', 'Tactical RPG', 'Tanks', 'Team-Based', 'Tennis', 'Text-Based', 'Third Person', 'Third-Person Shooter', 'Thriller', 'Tile-Matching', 'Time Attack', 'Time Management', 'Time Manipulation', 'Time Travel', 'Top-Down', 'Top-Down Shooter', 'Touch-Friendly', 'Tower Defense', 
    'TrackIR', 'Trading', 'Trading Card Game', 'Traditional Roguelike', 'Trains', 'Transhumanism', 'Transportation', 'Trivia', 'Turn-Based', 'Turn-Based Combat', 'Turn-Based Strategy', 'Turn-Based Tactics', 'Tutorial', 'Twin Stick Shooter', 'Typing', 'Underground', 'Underwater', 'Unforgiving', 'Utilities', 'VR', 'VR Only', 'Vampire', 'Vehicular Combat', 'Video Production', 'Vikings', 'Villain Protagonist', 'Violent', 'Visual Novel', 'Voice Control', 'Volleyball', 'Voxel', 'Walking Simulator', 'War', 'Wargame', 'Warhammer 40K', 'Web Publishing', 
    'Well-Written', 'Werewolves', 'Western', 'Wholesome', 'Word Game', 'World War I', 'World War II', 'Wrestling', 'Zombies', 'e-sports']

export const CATEGORIES = ['Cross-Platform Multiplayer', 'Family Sharing', 'In-App Purchases', 'Co-op', 'Adjustable Difficulty', 'Adjustable Text Size', 'Camera Comfort', 'Captions available', 'Chat Speech-to-text', 'Chat Text-to-speech', 'Color Alternatives', 
    'Commentary available', 'Custom Volume Controls', 'Full controller support', 'HDR available', 'Includes Source SDK', 'Includes level editor', 'Keyboard Only Option', 'LAN Co-op', 'LAN PvP', 'MMO', 'Mods', 'Mods (require HL2)', 'Mouse Only Option', 'Multi-player', 'Narrated Game Menus', 'Online Co-op', 'Online PvP', 'Partial Controller Support', 'Playable without Timed Input', 'PvP', 
    'Remote Play Together', 'Remote Play on Phone', 'Remote Play on TV', 'Remote Play on Tablet', 'Save Anytime', 'Shared/Split Screen', 'Shared/Split Screen Co-op', 'Shared/Split Screen PvP', 'Single-player', 'Stats', 'Steam Achievements', 'Steam Cloud', 'Steam Leaderboards', 'Steam Timeline', 'Steam Trading Cards', 'Steam Turn Notifications', 'Steam Workshop', 'SteamVR Collectibles', 'Stereo Sound', 'Subtitle Options', 'Surround Sound', 'Touch Only Option', 'Tracked Controller Support', 
    'VR Only', 'VR Support', 'VR Supported', 'Valve Anti-Cheat enabled'] 

export const LANGUAGES = ['English', 'Russian', 'German', 'Spanish', 'French', 'Irish', 'Italian', 'Japanese', 'Traditional Chinese', 'Korean'];

export const PUBLISHER_CLASS_OPTIONS = ['AAA', 'AA', 'Indie', 'Hobbyist'];

export const DEVELOPER_OPTIONS = ['Valve', 'KRAFTON, Inc.', 'Respawn', 'Bungie', 'Rockstar North', 
    'Larian Studios', 'Digital Extremes', 'CD PROJEKT RED', 'ZeniMax Online Studios', 'Ubisoft Montreal', 'Sledgehammer Games,Treyarch,Infinity Ward,Beenox,Raven Software,High Moon Studios,Demonware', 'FromSoftware Inc.', 'Arrowhead Game Studios', 'Behaviour Interactive Inc.', 'Facepunch Studios', 'Smilegate RPG', 'Pocketpair', 'Gaijin Entertainment', 'Rockstar Games', 
    'Paradox Development Studio', 'Avalanche Software', '24 Entertainment', 'SCS Software', 'Square Enix', 'Studio Wildcard,Instinct Games,Efecto Studios,Virtual Basement LLC', 'Hello Games', 'CREATIVE ASSEMBLY,Feral Interactive (Linux),Feral Interactive (Mac)', 'Firaxis Games,Aspyr (Mac),Aspyr (Linux)', 'CAPCOM Co., Ltd.', 'CREATIVE ASSEMBLY,Feral Interactive (Mac),Feral Interactive (Linux)', 
    'Rare Ltd', 'Bethesda Game Studios', 'Bohemia Interactive', 'FromSoftware', 'Techland', 
    'Grinding Gear Games', 'Colossal Order Ltd.', 'Endnight Games Ltd', 'ConcernedApe', 'Treyarch,Aspyr (Mac)', 'Playground Games', '343 Industries,Splash Damage,Ruffian Games,Bungie,Saber Interactive', 'KONAMI', 'Kinetic Games', 'Ludeon Studios', 'Titan Forge Games', 'Paradox Development Studio,Paradox Tinto', 'Redbeet Interactive', 'FromSoftware, Inc.', 
    'Iron Gate AB', 'Amazon Games', 'Wargaming Group Limited', 'Re-Logic', 'Offworld', 'VOID Interactive', 'Ubisoft Montreal,Red Storm,Ubisoft Shanghai,Ubisoft Toronto,Ubisoft Kiev', 'TaleWorlds Entertainment', 'The Indie Stone', 'Hazelight', 'EA Canada & EA Romania', 'BeamNG', 'id Software', 'Zeekerss', 'Ghost Ship Games', 'Wube Software LTD.', 'Supergiant Games', 'Ubisoft Montreal,Ubisoft Quebec,Ubisoft Toronto,Blue Byte', 
    'Respawn Entertainment', 'Klei Entertainment', 'Treyarch', 'Expansive Worlds', 'Coffee Stain Studios', 'Infinity Ward,Raven Software,Beenox,Treyarch,High Moon Studios,Sledgehammer Games,Activision Shanghai,Demonware,Toys for Bob', 'Crytek', 'Guerrilla', 'Nicalis, Inc.,Edmund McMillen', 'Gearbox Software,Aspyr (Mac),Aspyr (Linux)', 'Hopoo Games', 'Ubisoft Quebec,Ubisoft Montreal,Ubisoft Bucharest,Ubisoft Singapore,Ubisoft Montpellier,Ubisoft Kiev,Ubisoft Shanghai',
    'Gearbox Software', 'OVERKILL - a Starbreeze Studio.', 'Blue Mammoth Games', 'Funcom', 'Frontier Developments', 'Crystal Dynamics,Eidos-Montréal,Feral Interactive (Mac),Feral Interactive (Linux),Nixxes', 'Maxis', 'Unknown Worlds Entertainment', 'Eleventh Hour Games', 'DICE', 'The Fun Pimps', 'Warhorse Studios', 'Ubisoft Paris,Ubisoft Annecy,Ubisoft Bucharest,Ubisoft Montpellier,Ubisoft Milan,Reflections,Ubisoft Belgrade', 'Beat Games', 'Broadsword', 'CREATIVE ASSEMBLY,Feral Interactive', 
    'Square Enix,PlatinumGames Inc.', 'Cryptic Studios', 'Stunlock Studios'];

export const PUBLISHER_OPTIONS = ['Valve', 'KRAFTON, Inc.', 'Electronic Arts', 'Bungie', 'Rockstar Games', 'Larian Studios', 'Digital Extremes', 'CD PROJEKT RED', 'Bethesda Softworks', 'Ubisoft', 'Activision', 'FromSoftware Inc.,Bandai Namco Entertainment', 'PlayStation Publishing LLC', 'Behaviour Interactive Inc.', 'Facepunch Studios', 'Amazon Games', 'Pocketpair', 'Gaijin Network Ltd', 'Paradox Interactive', 'Warner Bros. Games', 'NetEase Games Global', 'SCS Software', 'Square Enix', 'Studio Wildcard,Snail Games USA',
    'Hello Games', 'SEGA,Feral Interactive (Linux),Feral Interactive (Mac)', '2K,Aspyr (Mac),Aspyr (Linux)', 'CAPCOM Co., Ltd.', 'SEGA,Feral Interactive (Mac),Feral Interactive (Linux)', 'Xbox Game Studios', 'Bohemia Interactive', 'Activision (Excluding Japan and Asia),FromSoftware (Japan),Рокстар (Asia)', 'Techland', 'Grinding Gear Games', 'Newnight', 'ConcernedApe', 
    'Activision,Aspyr (Mac)', 'Endnight Games Ltd', 'KONAMI', 'Kinetic Games', 'Ludeon Studios', 'Hi-Rez Studios', 'Axolot Games', 'FromSoftware, Inc.,Bandai Namco Entertainment', 'Coffee Stain Publishing', 'Wargaming Group Limited', 'Re-Logic', 'Offworld', 'VOID Interactive', 'TaleWorlds Entertainment', 'The Indie Stone', 'BeamNG', 'Zeekerss', 'Wube Software LTD.', 'Supergiant Games', 'Klei Entertainment', 'Expansive Worlds', 'Crytek', 'Nicalis, Inc.', 'Gearbox Publishing'];